title: Ismael Mousa
logo: /assets/img/ismael.jpg
description: ğŸ•Šï¸ Ù„ÙŠÙƒÙ†
url: "https://IsmaelMousa.github.io"
baseurl: ""

author:
  name: Ismael Mousa
  email: ismaelramzimousa@gmail.com

social:
  linkedin_username: IsmaelMousa
  github_username: IsmaelMousa

markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/

paginate: 5
paginate_path: "/page:num/"

timezone: Asia/Hebron
